### ISSUE TITLE
Please pick a license

### ISSUE THREAD

**Issue by allardhoeve** [intelie/django-oidc-auth#11]
Hey there, please pick a license and put it in LICENSE. Django suggests using BSD:

https://docs.djangoproject.com/en/1.9/intro/reusable-apps/

**Comment by lsmag** [comment]
Hi again @allardhoeve ,

Sure, we'll look into that. This project has been stale for a while because the code as it stands right now suits our needs (hence why it didn't support Django 1.9 until your PR), but I'll be more active here and then push an update to PyPI.

**Comment by koriaf** [comment]
This task is important; it's pointless to invest time and use this library without proper knowledge about it's licence. Technically, this code can't be used in some jurisdictions at all without the licence, and picking a one shall be not so time-consuming tasks.

Hope you'll attend it :-)
