### ISSUE TITLE
Last pip package version is 0.0.5

### ISSUE THREAD

**Issue by oliamb** [intelie/django-oidc-auth#4]
https://pypi.python.org/pypi/django-oidc-auth

The last published version is 0.0.5 but the latest tag is 0.0.10, why is there such a difference?

**Comment by tsudot** [comment]
Also 0.0.5 throws errors with Django 1.8.4

```
    from jwkest.jwk import load_jwks_from_url
ImportError: cannot import name load_jwks_from_url
```

Best is to install using directly from github

    pip install git+https://github.com/intelie/django-oidc-auth.git
